package com.qdu.pojo;
// Generated 2017-7-31 11:30:17 by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private int aid;
     private String aname;
     private String apwd;

    public Admin() {
    }

    public Admin(int aid, String aname, String apwd) {
       this.aid = aid;
       this.aname = aname;
       this.apwd = apwd;
    }
   
    public int getAid() {
        return this.aid;
    }
    
    public void setAid(int aid) {
        this.aid = aid;
    }
    public String getAname() {
        return this.aname;
    }
    
    public void setAname(String aname) {
        this.aname = aname;
    }
    public String getApwd() {
        return this.apwd;
    }
    
    public void setApwd(String apwd) {
        this.apwd = apwd;
    }




}


