package com.qdu.pojo;
// Generated 2017-7-31 11:30:17 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private int cid;
     private Students studentsByPid;
     private Students studentsBySid;
     private String comment;

    public Comment() {
    }

	
    public Comment(int cid, Students studentsByPid, Students studentsBySid) {
        this.cid = cid;
        this.studentsByPid = studentsByPid;
        this.studentsBySid = studentsBySid;
    }
    public Comment(int cid, Students studentsByPid, Students studentsBySid, String comment) {
       this.cid = cid;
       this.studentsByPid = studentsByPid;
       this.studentsBySid = studentsBySid;
       this.comment = comment;
    }
   
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }
    public Students getStudentsByPid() {
        return this.studentsByPid;
    }
    
    public void setStudentsByPid(Students studentsByPid) {
        this.studentsByPid = studentsByPid;
    }
    public Students getStudentsBySid() {
        return this.studentsBySid;
    }
    
    public void setStudentsBySid(Students studentsBySid) {
        this.studentsBySid = studentsBySid;
    }
    public Serializable getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


