package com.qdu.pojo;
// Generated 2017-7-31 11:30:17 by Hibernate Tools 4.3.1



/**
 * FansStatus generated by hbm2java
 */
public class FansStatus  implements java.io.Serializable {


     private int record;
     private String pid;
     private String sid;
     private Integer astatus;

    public FansStatus() {
    }

	
    public FansStatus(int record, String pid, String sid) {
        this.record = record;
        this.pid = pid;
        this.sid = sid;
    }
    public FansStatus(int record, String pid, String sid, Integer astatus) {
       this.record = record;
       this.pid = pid;
       this.sid = sid;
       this.astatus = astatus;
    }
   
    public int getRecord() {
        return this.record;
    }
    
    public void setRecord(int record) {
        this.record = record;
    }
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public String getSid() {
        return this.sid;
    }
    
    public void setSid(String sid) {
        this.sid = sid;
    }
    public Integer getAstatus() {
        return this.astatus;
    }
    
    public void setAstatus(Integer astatus) {
        this.astatus = astatus;
    }




}


