package com.qdu.pojo;
// Generated 2017-7-31 11:30:17 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Information generated by hbm2java
 */
public class Information  implements java.io.Serializable {


     private int rid;
     private Students students;
     private String photo;
     private String workExp;
     private String skill;
     private String selfAsse;

    public Information() {
    }

	
    public Information(int rid, Students students, String photo, String workExp, String skill) {
        this.rid = rid;
        this.students = students;
        this.photo = photo;
        this.workExp = workExp;
        this.skill = skill;
    }
    public Information(int rid, Students students, String photo, String workExp,String skill,String selfAsse) {
       this.rid = rid;
       this.students = students;
       this.photo = photo;
       this.workExp = workExp;
       this.skill = skill;
       this.selfAsse = selfAsse;
    }
   
    public int getRid() {
        return this.rid;
    }
    
    public void setRid(int rid) {
        this.rid = rid;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getWorkExp() {
        return this.workExp;
    }
    
    public void setWorkExp(String workExp) {
        this.workExp = workExp;
    }
    public String getSkill() {
        return this.skill;
    }
    
    public void setSkill(String skill) {
        this.skill = skill;
    }
    public String getSelfAsse() {
        return this.selfAsse;
    }
    
    public void setSelfAsse(String selfAsse) {
        this.selfAsse = selfAsse;
    }




}


